// projects/ToDoList/src/components/TaskList.vue
<!-- Css -->
<style>
  @import '../assets/css/tasklist.css';
</style>

<!-- JS -->
<script src="../assets/js/tasklist.js"></script>

<!-- Template -->
<template>
  <div id="todolist">
    <div>
      <h1 class="title">ToDo Lists</h1>
    </div>

    <div id="todolist_search">
      <input class="todolist_search--task" type="text" v-model="searchedTaskName" placeholder="Search task" />
    </div>
    
    <div id="todolist_list">
      <TaskForm v-on:addTask="addTast"/>

      <div class="todolist_list--tasks" v-if="tareas.length > 0">
        <Task v-for="task in filtredTask" 
          :key="task.nombre" 
          :task="task" 
          @taskChange="save"
          @removeTask="removeTask"/>
      </div>

      <footer class="todolist_list--actions">
        <span>{{ completedTask }} Items left</span>

        <div>
          <div>
            <input type="radio" id="all" value="All" v-model="filteredStatus" checked>
            <label class="clickable" for="all">All</label>
          </div>
          <div>
            <input type="radio" id="active" value="Active" v-model="filteredStatus">
            <label class="clickable" for="active">Active</label>
          </div>
          <div>
            <input type="radio" id="completed" value="Completed" v-model="filteredStatus">
            <label class="clickable" for="completed">Completed</label>
          </div>
        </div>

        <span class="clickable" v-on:click="removeCompletedTasks()">Clear Completed</span>
      </footer>
    </div>
  </div>
</template>

// projects/ToDoList-Angular/src/app/task-list/task-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Priorities } from 'src/assets/js/Priorities';
import { Task } from 'src/assets/js/Task';
import { StorageManager } from '../../assets/js/Storage';

@Component({
  selector: 'task-list',
  templateUrl: './task-list.component.html',
  styleUrls: ['./task-list.component.sass']
})
export class TaskListComponent implements OnInit {

  public tasks: Array<Task>;
  public filteredStatus: string;
  public searchedTaskName: string;

  constructor() { 
    this.tasks = [];
    this.filteredStatus = 'All';
    this.searchedTaskName = '';
  }

  ngOnInit(): void {
    this.tasks = StorageManager.getTasks();
  }

  public addTast(task: Task): void {
    task.setId(this.tasks.length); 
    this.tasks.splice(0, 0, task);
    this.save();
  }

  public removeTask(task: Task): void {
      this.tasks.splice(this.tasks.indexOf(task), 1);
      this.save();
  }

  public removeCompletedTasks() {
      this.tasks = this.tasks.filter( (task: Task) => !task.isCompleted() );
      this.save();
  }

  public save(): void {
    StorageManager.saveTasks(this.tasks);
  }

  completedTask() {
    return Array.from(this.tasks).filter( (task: Task) => !task.isCompleted() ).length;
  }

  filtredTask() {
    let filteredList: Array<Task> = Array.from(this.tasks).filter((task: Task) => {
      let result: boolean = true;
      if (this.filteredStatus != 'All') {
        if (this.filteredStatus == 'Active') {
          result = !task.isCompleted();
        } else if (this.filteredStatus == 'Completed') {
          result = task.isCompleted();
        }
      }
      return result && task.getNombre().includes(this.searchedTaskName);
    });

    return Array
      .from(filteredList)
      .sort((taskA: Task, taskB: Task) => Priorities.compare(taskB.getPriority(), taskA.getPriority()));
  }
}

<div id="todolist">
    <div>
      <h1 class="title">ToDo Lists</h1>
    </div>

    <div id="todolist_search">
      <input class="todolist_search--task" type="text" [(ngModel)]="searchedTaskName" placeholder="Search task" />
    </div>
    
    <div id="todolist_list">
      <TaskForm (addTask)="addTast($event)"/>

      <div class="todolist_list--tasks" *ngIf="tareas.length > 0">
        <Task *ngFor="let task of filtredTask"
            attr.task="task" 
            (taskChange)="save($event)"
            (removeTask)="removeTask($event)"/>
      </div>

      <footer class="todolist_list--actions">
        <span>{{ completedTask }} Items left</span>

        <div>
          <div>
            <input type="radio" id="all" value="All" [(ngModel)]="filteredStatus" checked>
            <label class="clickable" for="all">All</label>
          </div>
          <div>
            <input type="radio" id="active" value="Active" [(ngModel)]="filteredStatus">
            <label class="clickable" for="active">Active</label>
          </div>
          <div>
            <input type="radio" id="completed" value="Completed" [(ngModel)]="filteredStatus">
            <label class="clickable" for="completed">Completed</label>
          </div>
        </div>

        <span class="clickable" (click)="removeCompletedTasks($event)">Clear Completed</span>
      </footer>
    </div>
  </div>
